/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rescate;

/**
 *
 * @author Jorge
 */
public enum AccionBombero {
    //IMPLEMENTADAS
    NUEVO_TURNO, FINALIZAR_TURNO,
    MOVER_NORTE, MOVER_ESTE, MOVER_SUR, MOVER_OESTE, //Movimiento
    EXTINGUIR_NORTE, EXTINGUIR_ESTE,EXTINGUIR_SUR, EXTINGUIR_OESTE, //Manguerita
    ABIR_PUERTA_NORTE,ABIR_PUERTA_ESTE, ABIR_PUERTA_SUR,ABIR_PUERTA_OESTE, //Abrir puertas
    CERRAR_PUERTA_NORTE, CERRAR_PUERTA_ESTE, CERRAR_PUERTA_SUR, CERRAR_PUERTA_OESTE, //Cerrar puertas
    
    //NO IMPLEMENTADAS YET
    DERRIBAR_PARED_NORTE, DERRIBAR_PARED_ESTE, DERRIBAR_PARED_SUR, DERRIBAR_PARED_OESTE,  //Derribar paredes
    TRASLADAR_SUPERVIVIENTE_NORTE, TRASLADAR_SUPERVIVIENTE_ESTE,TRASLADAR_SUPERVIVIENTE_SUR,TRASLADAR_SUPERVIVIENTE_OESTE, //Trasladar superviviente
    TRASLADAR_MATERIA_PELIGROSA_NORTE,TRASLADAR_MATERIA_PELIGROSA_ESTE, TRASLADAR_MATERIA_PELIGROSA_SUR, TRASLADAR_MATERIA_PELIGROSA_OESTE; //Trasladar materias peligrosas
}
